### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by KokoseiJ** [KokoseiJ/DiscordBot#2]
# Code
 * [x] add perm command which contains help, set(which contains user, module subcommands) subcommands
 * [x] add set_prefix command
 * [ ] Migrate datas to SQLite
 * [ ] print "Running {cmd}..." before running the command.
 * [ ] Add an exception that will be raised by modules when It's expected
 * [ ] Remove unnecessary async/await keywords
 * [ ] change type detection to use `isinstance()`
 * [ ] Split modules folder to modules and filters folder
 * [ ] Change permission type, 1~8 should be able to be used by users
 * [ ] on_ready handler:  Do something in here, like changing the activity for every single second
 * [ ] Filters, but not just on_messages event but all events
 * [ ] DEBUGGING

# Modules
 * [x] translate 음악 module to english.
 * [x] Add help module that will display the list of commands.
 * [ ] add docstring and comments to every modules
 * [ ] Add filter module which will allow users to add their own filters
 * [ ] Nico module is broken due to nicovideo changing their website design - Fix is required

# Documentation
 * [x] Provide a documentation about the bot itself
 * [x] Move TODO section to github TODO list
 * [ ] Provide more detailed documentation about my bot
 * [ ] Provide a documentation about each modules
 * [ ] Provide a documentation about the format of the module
